### ISSUE TITLE
[VERSION TRACK] 2.2.5 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#105]
# Known Bugs - v2.2.5

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
- [x] __2.2.2__ Need some enhancements to the version compare - button to fix, modhub version when applicable, notification on main screen, and proper sorting - #106 
- [x] __2.2.2__ Update glob package (API breaking change) - #108  
- [x] __2.2.3__ Malformed iconFilename entry could cause crashes - #110 
- [x] __2.2.3__ Add notes field for in-game admin password, and a button to copy it to the clipboard.  
- [x] __2.2.4__ Version compare still misses some. #113 
- [x] __2.2.4__ Add some extra error checking to game launch. #116 
- [x] Still some oddities for smaller window sizes on non-english languages. (overflowed layout, etc)
