### ISSUE TITLE
[VERSION TRACK] v2.5.0 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#126]
# Known Bugs - v2.5.0
This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
 - [x] Possible Feature add #122 - Vehicle/Implement Listing in description
 - [x] Possible Feature add #125  - Folder/Collection Last used tracking
 - [x] Button tooltip wrong #127 
 - [x] Crop calendar offset non-functional #129   (requires cache rebuild if you have southern maps)
 - [x] Units on mod look screens should be translatable.
 - [x] Change XML parsing library to fast-xml-parser #130 and #133 
 - [x] Fix crash on new FS22 install #131
 - [x] Add direct savegame compare when the savegame is in a collection (for instance, downloads)

**Comment by jtsage** [comment]
# 2.3.0 IS BROKEN - PLEASE STAND BY FOR 2.4.0

**Comment by vitalii2011** [comment]
If possible/not difficult, please add lines for translation: 
![Image 002](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/56b2d226-851c-4174-924a-560f29fb3126)
```
"hp": "л. с.",
"kph": "км/ч",
"mph": "миля/ч",
"m": "м",
"kg": "кг",
"t": "т",
``` 
Of course, except for "hp", everything will be intuitively understandable and without translation to users with any knowledge of the English language. :)

**Comment by jtsage** [comment]
Sure, I'll get this in today probably, it will be in the next build.  That's my fault, I am well aware those units are translatable.  Thanks!
