### ISSUE TITLE
[VERSION TRACK] v2.6.1 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#134]
# Known Bugs - v2.6.1

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List

- [x] (fix: 2.6.1) Crash on incorrect `<modFilename>` entry - #131 
- [x] (added: 2.7.0) Additional filtering / information in game log display. - #138 
- [x] (added: 2.7.0) Offline / Removable storage option for collections - #139 
- [x] (fix: 2.7.0) Fix for unusual version strings being seen as numbers instead of strings.
- [x] (added 2.7.0) Add option to track mod adds to savegames using backups - #140 
- [x] (fix: 2.7.0) Fix modHub data - #141
