### ISSUE TITLE
[VERSION TRACK] v3.0.0 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#157]
# Known Bugs - v3.0.0
This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
- [x] Mod Download from dedi server - progress meter broken
- [x] Crop Calendars are wrong again
- [x] #160 - empty log file

## v3.1.0 Roadmap
- [x] string-too-long error on very large collections - rethink mod-icon storage
- [x] savegame management
- [x] Explicitly mark nested collections. #169 
- [x] Change game units per-collection. #167 
- [x] ~~Explore copy/move/delete/import popup windows being part of main window. I might hate this, but gonna see what it looks like.~~ (it would break workflows all over the place)

## Release Canidates:

- v3.1.0-RC1 : https://github.com/FSGModding/FSG_Mod_Assistant/releases/tag/v3.0.91

## Full Change Log
- Auto-translate new strings for l10n entries
- Catch non-array badge structure
- Fix window minimization - most child windows should not be true children
- Add color coding to mod detail window
- Add map overview image in mod maps (detail window)
- Fix savegame detection logic on right-click actions
- Detect log files in collections, allow direct open in the log viewer
- Re-write mod cache module, add scaling of dds files where possible
- Fix server download status display
- Add "clear log" button to log viewer
- Add local savegame manager with ZIP import
- Add ability to import ZIP pack directly (drag & drop)
- Fix ZIP export to allow folders
- Add unit configuration per-collection (miles / temperature / acres / money)

**Comment by BlurpleGirl** [comment]
Hi, I just got the update, right before the update I couldn't click on anything (like I couldn't see mod details) then I closed it and then reopened it and there was an update so I installed the update and now there's no folders to see :(

I'm going to try to roll back to the prev version if I can.

**Comment by aashton188** [comment]
ya i cant even lauch the app it gives me a error after 5 seconds of being open

**Comment by BlurpleGirl** [comment]
so now I'm on 3.0 I was forced back onto 3.0 

it works pretty much but I noticed that double clicking to bring up the details kinda lags and if I minimize the details window I can't get back or at least I'm not sure where to look but restarting it is a piece of cake. 

when I use the search all, that definitely takes a lot more time and has significant waiting; doesn't mean its buggy and may just be the way it is.

**Comment by vitalii2011** [comment]
Just wondering: is this how it's supposed to be?

https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/9f1c5de5-c17b-4ba3-aebb-2eee3436cdb3

**Comment by jtsage** [comment]
Hah.  no.  Looks like it's not computing correctly.  The new numbers are supposed to be:

Current Cache size: [mod details] / [mod icons]

Current Detail : [stuff you have opened in the detail window that had store items, auto-expires after a few days to keep the size down]

But it shouldn't drop to zero when you hit the clean button, thanks.

**Comment by vitalii2011** [comment]
If it matters, I use the portable version.

**Comment by jtsage** [comment]
It shouldn't.  Probably a race condition - because the original storage library was atomic (read/write for every get and set), the "clean cache" reads the whole file, removes non-existent mods, and writes it back to disk - I'm betting when I refactored, it no longer waits for it to write it back - so the size calculation math might be happening in the middle of the write - which would fail or report nonsense, so the error trapping is going to default to zero instead.  I'll check to be sure, but chances are I just need to make sure the write is complete before asking how big the file is.
