### ISSUE TITLE
[VERSION TRACK] v3.5.1 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#222]
# Known Bugs - v3.5.1
This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
- [x] A way to export Mod Assistant settings would be nice. (and re-import them of course)
- [x] ZIP Library shortcomings discovered #223 
- [x] (3.5.1) Collection Settings window was failing when multi version mode was off. 
- [x] (3.5.2) Brand new installs were failing to open #225  
- [x] Keep scroll position when editing folders #228 
- [x] light mode icons are wrong again
- [x] need select all on mod external site, need option to clear it.
- [x] Add an option to backup gameSettings.xml and game.xml for the case where it gets corrupted?
- [x] map PDA's are broken again
- [x] find a better way to force-save the last edited "note" on details page
- [x] add a flag for "Set active" when editing a details page item that requires pressing it. or maybe a popup
- [x] something is very wrong with reading unzipped mods (current -dev)

**Comment by jtsage** [comment]
Sorry about the double release notification, found a last minute bug with the auto updater.  Also, if you were running one of the 3.5.0-RC's you may have noticed the thrown error message when clicking the "Apply Update" button.  Fixed in the release.

**Comment by vitalii2011** [comment]
![Image 001](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/6e3b2f84-ff40-48d9-afeb-ed5ba1ff9d2f)

**Comment by jtsage** [comment]
yeah, I changed how I was storing that info last minute - hit the clear button and the new entries will actually make sense.  I meant to include that in a note on the release

**Comment by aurelien2023** [comment]
Hi, I've an issue since 3.4.97 at least :
nothing appears in the edit folder  details (In French at least...)

![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/60996361/31e77cf5-4a81-49eb-afa5-37ae2b19a578)

**Comment by aurelien2023** [comment]
> Hi, I've an issue since 3.4.97 at least : nothing appears in the edit folder details (In French at least...)
> 
> ![image](https://private-user-images.githubusercontent.com/60996361/304335076-31e77cf5-4a81-49eb-afa5-37ae2b19a578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTIzMjksIm5iZiI6MTcwNzgxMjAyOSwicGF0aCI6Ii82MDk5NjM2MS8zMDQzMzUwNzYtMzFlNzdjZjUtNGE4MS00OWViLWFmYTUtMzdhZTJiMTlhNTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4MTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YTM3YzMxOTAyM2Y5YjU1MTQ0NjhjYzdlODc1ZmMxNjBiMDU0NWFmNWExNzJkNWEwNmZmYzVmZDJmNTVhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.acu8D4LMv1a15ti2wBoUIn8gvvIfHd6IMgunDB7alRM)

I try to set the language in English => It works again!! => then go back to French : didn't work => go back to English => Don't work anymore !!! 😢

**Comment by vitalii2011** [comment]
![0010](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/e32af28b-dfed-45d3-a45a-c7309618ea66)

**Comment by MeRida2104** [comment]
I have the same issue with german language:

It looks like this:

![image](https://github.com/FSGModding/FSG_Mod_Assistant/assets/96819380/18c812b9-0e41-45a3-8154-728c0f8554f8)

**Comment by vitalii2011** [comment]
?:
![Screenshot 2024-02-13 at 14-49-17 FSGModding_FSG_Mod_Assistant Farming Simulator 22 Mod Manager](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/d39bce3f-15a4-45ac-aee2-118e78bb8ff1)

**Comment by jtsage** [comment]
Regarding the Collection Details not showing - I have no idea why it does work sometimes for English, but it's actually tied to multi-version mode - when it's off, there is nothing in those settings windows.  I'll push a fix shortly here, but in the meantime, if you turn on multi-version mode, the problem disappears

**Comment by jtsage** [comment]
> ?: ![Screenshot 2024-02-13 at 14-49-17 FSGModding_FSG_Mod_Assistant Farming Simulator 22 Mod Manager](https://private-user-images.githubusercontent.com/41552153/304398421-d39bce3f-15a4-45ac-aee2-118e78bb8ff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzQ0OTcsIm5iZiI6MTcwNzgzNDE5NywicGF0aCI6Ii80MTU1MjE1My8zMDQzOTg0MjEtZDM5YmNlM2YtMTVhNC00NWFjLWFlZTItMTE4ZTc4YmI4ZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE0MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYWFiZjdiZDE0ZjA5ZWU4Y2I4NWM3ZDk5ZGU5OWI2Y2VjMzg2MzFjOTU1MmNmNWNjNzA4NzQxZGFjZDVmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQG3ZPPrmKAIJjeMgKVLdMfDI_aU70KOYbVcMXwXVlA)

yeah, that's out of date, removed, and I'll stop adding it every time.

**Comment by MeRida2104** [comment]
it works again :)

**Comment by vitalii2011** [comment]
The icons of the context menu items are not adapted/the color is not inverted to the Light theme:
![0010](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/47541809-3537-45a0-8cd1-24dbdd24b25b)

**Comment by vitalii2011** [comment]
- It’s not possible to remove the “WWW” tag after adding a link if it no longer exists, for example, for: https://mods.mygamesteam.com/mod/fs22-fendt-katana-850-4/
- The “Select all” item is missing: 
![0010](https://github.com/FSGModding/FSG_Mod_Assistant/assets/41552153/be26ea54-8bf2-45db-8180-60af7fec9d4d)
