### ISSUE TITLE
[VERSION TRACK] v4.0.0  Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#236]
# Known Bugs - v4.0.0

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
- [x] In some cases, the bootstrap tooltips fail to disperse. #234 
- [x] In the case of an empty farms.xml in a save, local savegame manager will error. #237 
- [x] Log file viewer overscrolls and jumps at end of file. #235 
- [x] Feature: add a confirm dialog for removing a folder from tracking
- [x] Feature: add the alpha-sort for folders back
- [x] Feature: smaller mini-mode
- [x] UI Bug: missing folder modal can get lost.

## Build Plans
- 4.0.1 - Estimated 2024-04-07 to fix #234, #235, #237 and add folder confirm dialog. 
- 4.0.2 - Estimated 2024-05-17 to add back folder alpha, some bug fixes.

**Comment by jtsage** [comment]
Keeping same issue, marker for 4.0.2 release.
