### ISSUE TITLE
[RELEASE TRACK] 2.0.1 Bug List & Known Issues (v2.1.0 Changes)

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#65]
# Known Bugs - v2.0.1

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us. Note that all these fixes have been postponed to 2.1.0, due approx Feb 11

## Issue List
 - [x] Duplicate L10N code #66 02161f0
 - [x] Color themes (system) #67 b4386cd cb71308
 - [x] Ability to select all/none in the Copy Favorites and Import screens.  02161f0
 - [x] We like the new titlebar on main window, repeat that change through the app. cb71308
 - [x] Allow canceling of direct dedi download. #68 ba95726
 - [x] "Deactivated" shows as "Unknown" caa9cbb
 - [x] Documentation is already outdated, rebuild.
 - [x] Need the context clues a bit more clear on the detail window #73 583d74c
 - [x] It'd be nice to be able to open the modhub page for a mod direct from the savegame compare screen
 - [x] Scrollbar contrast is too low. addc74d
 - [x] Ability to use with more than just FS22 - FS19, FS17, FS15, and FS13 are similar enough in design that the only major changes are to the UI.  This will be an opt-in mode, hidden by default. #69 
 - [x] Context menu copy on the game log and debug log 40d46ea 
 - [x] Context menu cut/copy/paste in filter bar(s) ad66702
 - [x] Mod sorting is not case insensitive a31f365
 - [x] Badge/Tag/Category text is too small now ad66702
 - [x] Add modHub info for 19,17,15 f153ec6
 - [x] Tooltip placement for top bar buttons is sometimes bad, force it. #74 bc5df34
 - [x] `PCOnly` only makes sense in a FS22 context, nonModHub is not applicable to FS13. ca03e05
 - [x] Per the changes in #69, need a way to load the game log for each. dc08049
 - [x] Version checker guesses the wrong latest version. #76 f7aaba2
 - [x] Code refactor introduced huge regressions with badge display and savegame compare.  2d981a4
 - [x] Drag-and-Drop would be way more convient for the savegame compare. dd94199

**Comment by vitalii2011** [comment]
Is it possible for the slider on the scroll bar to have a more contrasting color?  It's hard to see where he is right now.

**Comment by jtsage** [comment]
> Is it possible for the slider on the scroll bar to have a more contrasting color? It's hard to see where he is right now.

Heh.  I was thinking this just last night.  Yeah, I'll give it a tweak.

**Comment by vitalii2011** [comment]
> Heh. I was thinking this just last night. Yeah, I'll give it a tweak.

Only the slider (and labels for the location of the selected mods), not the background of the scrollbar:
![GIF](https://user-images.githubusercontent.com/41552153/217207346-489eeea1-b620-4c3b-b439-a2f8d8d0d41a.gif)

**Comment by vitalii2011** [comment]
Is it possible, when viewing the log, to add commands to the context menu by right-clicking the mouse?
![Image 001](https://user-images.githubusercontent.com/41552153/217825688-2df99ea5-dd08-4419-953b-58533071f8c6.png)

**Comment by jtsage** [comment]
> Is it possible, when viewing the log, to add commands to the context menu by right-clicking the mouse? ![Image 001](https://user-images.githubusercontent.com/41552153/217825688-2df99ea5-dd08-4419-953b-58533071f8c6.png)

Sure.  You want it by line, or by highlighted text? (highlighted seems to make more sense to me)

**Comment by vitalii2011** [comment]
> by highlighted text?

**Comment by vitalii2011** [comment]
- Letter case in mod names should not be taken into account.
- Due to the decrease in the distance between the characters in the category names (if there was any), the inscriptions became difficult to read. 
![0010](https://user-images.githubusercontent.com/41552153/218079151-7798ea72-8b1b-44b0-836b-9214b123ec88.png)

**Comment by vitalii2011** [comment]
![0013](https://user-images.githubusercontent.com/41552153/218112799-957ac388-2a93-46ac-a497-59d76dbe1681.png)

**Comment by jtsage** [comment]
> * Letter case in mod names should not be taken into account. **[done]**
> * Due to the decrease in the distance between the characters in the category names (if there was any), the inscriptions became difficult to read.

How bout this for the tags?

![2023-02-10 10_03_43-FSG Mod Assistant](https://user-images.githubusercontent.com/605986/218124706-420b505c-772c-47da-b402-46aeb28c411f.png)
![2023-02-10 10_05_04-FSG Mod Assistant](https://user-images.githubusercontent.com/605986/218124949-a149e05d-ee80-4769-9971-b4788ab515c8.png)

Lightened the weight of the font, upped the size, and added some extra spacing between letters.  Agreed, it was hard to read

**Comment by vitalii2011** [comment]
> Как насчет тегов?
> Уменьшен вес шрифта, увеличен размер и добавлен дополнительный интервал между буквами. Согласен, тяжело читать
Great. Thank you very much.

**Comment by vitalii2011** [comment]
If it's not difficult, raise the text of titles/tags by 1 px (no more) up. Now (2.0.10) is too low, not very nice.
![2244](https://user-images.githubusercontent.com/41552153/218246952-51965d80-1b08-4600-baf0-eebb2c22830c.png)

**Comment by jtsage** [comment]
Closing in favor of #77 - thank you for all your bug reporting efforts!
