### ISSUE TITLE
[VERSION TRACK] 2.1.0/2.1.1 Bug List & Known Issues

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#77]
# Known Bugs - v2.1.0 / v2.1.1

This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List
- [x] Possible Addition - custom mod URL per mod - #70 6fd3ba0
- [x] Selection from savegame window is broken a5ab380 (fixed in 2.1.1)
- [x] Cut/Copy/Paste context menu items are not localized correctly. 9020810
- [x] Scroll bar highlight is not correctly clearing. 30c1e6f
- [x] Drag-and-Drop can guess wrongly that a single item is a folder [wont-fix (can't, really)]
- [x] Copy/Move overwrite issue - #82 6923dc1
- [x] Poor translation, DE - #84 a44e4fc
- [x] ModHub list is inaccurate - #85 
- [x] Multiple download at once fails - #83 
- [x] Download Speed / Time Remaining display - #83

**Comment by vitalii2011** [comment]
In versions newer than 2.0.1, selection does not work:
![Screenshot 2023-02-11 at 23-25-57 FSG Mod Assistant - Savegame Compare](https://user-images.githubusercontent.com/41552153/218279736-02605bcf-fdb3-4f88-b8bd-8e7a9af84736.png)
The Main Window overview opens, but mods are not highlighted.

**Comment by jtsage** [comment]
I'm gonna be pretty swamped at work this coming week, so if nothing else is found I will go ahead and push a new build tomorrow with that fix in it - seems like a pretty important bug fix to me.

**Comment by vitalii2011** [comment]
Thanks for 2.1.1.
Someday later, if you add lines for translation, I will try to translate these context menu items. )
![0010](https://user-images.githubusercontent.com/41552153/218332884-6e8bcf3a-fd44-4a5b-8aa9-b9cc15cb6221.png)
![0011](https://user-images.githubusercontent.com/41552153/218332886-dbe8ec88-4d95-4e63-8ff6-674844505836.png)

**Comment by jtsage** [comment]
Oh gross.  I used the default roles for those, I had hoped that it would follow the system language.  I will pull them out later today, and take a good guess at the strings I'll need for #70

**Comment by vitalii2011** [comment]
Location labels on the scrollbar are not reset:

https://user-images.githubusercontent.com/41552153/218342385-144fba5a-8a9d-48e1-95c3-52eff5756382.mp4

Reset when opening Settings.
